name: Ubuntu/Clang

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1.4
      with:
        version: latest
        platform: x64

    - name: Config & Build
      run:  |
          cmake . -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose -C ${{env.BUILD_TYPE}}
      



